In [1]:
from pathlib import Path
import pandas as pd

# 1. Loading

In [2]:
folder = Path(r"C:\Users\z3553082\OneDrive - UNSW\Documents\CICCADA - Data\solar edge\OneDrive_1_6-18-2026\data_2025_01_12_alias_zipped")

files = list(folder.glob("*.parquet"))
df = pd.concat((pd.read_parquet(f) for f in files), ignore_index=True)

df.head()

,site_alias,timestamp,active_power_1,active_power_2,active_power_3,reactive_power_1,reactive_power_2,reactive_power_3,ac_voltage_1,ac_voltage_2,ac_voltage_3,ac_frequency_1,ac_frequency_2,ac_frequency_3,derating_active_flag
0,AUS001,2025-01-18 10:56:00.000000,331.495239,NaN,NaN,133.485626,NaN,NaN,243.767776,NaN,NaN,49.964836,NaN,NaN,NaN
1,AUS001,2025-01-18 11:01:00.000000,358.739594,NaN,NaN,149.324783,NaN,NaN,244.220245,NaN,NaN,49.974575,NaN,NaN,NaN
2,AUS001,2025-01-18 11:06:00.000000,399.047180,NaN,NaN,149.562119,NaN,NaN,244.007385,NaN,NaN,49.972515,NaN,NaN,NaN
3,AUS001,2025-01-18 11:11:00.000000,307.645752,NaN,NaN,138.304642,NaN,NaN,244.569519,NaN,NaN,50.030102,NaN,NaN,NaN
4,AUS001,2025-01-18 11:16:00.000000,588.053894,NaN,NaN,150.843155,NaN,NaN,246.198456,NaN,NaN,49.972744,NaN,NaN,NaN

In [3]:
files

[WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_01_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_02_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_03_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_04_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_05_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_06_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_07_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_08_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_09_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_10_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_11_alias_zipped (1).parquet'),
 WindowsPath('C:/Users/z3553082/OneDrive - UNSW/Documents/CICCADA - Data/solar edge/OneDrive_1_6-18-2026/data_2025_01_12_alias_zipped/data_2025_12_alias_zipped (1).parquet')]

In [4]:
alias_path = Path(r"C:\Users\z3553082\OneDrive - UNSW\Documents\CICCADA - Data\solar edge\OneDrive_1_6-18-2026\alias_mapping_alias_only.csv")

alias_df = pd.read_csv(alias_path)   # or read all parquet files if it's a folder
df = df.merge(
    alias_df[["alias", "zip_code"]],
    left_on="site_alias",
    right_on="alias",
    how="left"
)

df.head()

,site_alias,timestamp,active_power_1,active_power_2,active_power_3,reactive_power_1,reactive_power_2,reactive_power_3,ac_voltage_1,ac_voltage_2,ac_voltage_3,ac_frequency_1,ac_frequency_2,ac_frequency_3,derating_active_flag,alias,zip_code
0,AUS001,2025-01-18 10:56:00.000000,331.495239,NaN,NaN,133.485626,NaN,NaN,243.767776,NaN,NaN,49.964836,NaN,NaN,NaN,AUS001,2291
1,AUS001,2025-01-18 11:01:00.000000,358.739594,NaN,NaN,149.324783,NaN,NaN,244.220245,NaN,NaN,49.974575,NaN,NaN,NaN,AUS001,2291
2,AUS001,2025-01-18 11:06:00.000000,399.047180,NaN,NaN,149.562119,NaN,NaN,244.007385,NaN,NaN,49.972515,NaN,NaN,NaN,AUS001,2291
3,AUS001,2025-01-18 11:11:00.000000,307.645752,NaN,NaN,138.304642,NaN,NaN,244.569519,NaN,NaN,50.030102,NaN,NaN,NaN,AUS001,2291
4,AUS001,2025-01-18 11:16:00.000000,588.053894,NaN,NaN,150.843155,NaN,NaN,246.198456,NaN,NaN,49.972744,NaN,NaN,NaN,AUS001,2291

In [5]:
df

,site_alias,timestamp,active_power_1,active_power_2,active_power_3,reactive_power_1,reactive_power_2,reactive_power_3,ac_voltage_1,ac_voltage_2,ac_voltage_3,ac_frequency_1,ac_frequency_2,ac_frequency_3,derating_active_flag,alias,zip_code
0,AUS001,2025-01-18 10:56:00.000000,331.495239,NaN,NaN,133.485626,NaN,NaN,243.767776,NaN,NaN,49.964836,NaN,NaN,NaN,AUS001,2291
1,AUS001,2025-01-18 11:01:00.000000,358.739594,NaN,NaN,149.324783,NaN,NaN,244.220245,NaN,NaN,49.974575,NaN,NaN,NaN,AUS001,2291
2,AUS001,2025-01-18 11:06:00.000000,399.047180,NaN,NaN,149.562119,NaN,NaN,244.007385,NaN,NaN,49.972515,NaN,NaN,NaN,AUS001,2291
3,AUS001,2025-01-18 11:11:00.000000,307.645752,NaN,NaN,138.304642,NaN,NaN,244.569519,NaN,NaN,50.030102,NaN,NaN,NaN,AUS001,2291
4,AUS001,2025-01-18 11:16:00.000000,588.053894,NaN,NaN,150.843155,NaN,NaN,246.198456,NaN,NaN,49.972744,NaN,NaN,NaN,AUS001,2291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86643180,AUS572,2025-12-14 18:41:04.000000,0.000000,NaN,NaN,-240.229630,NaN,NaN,234.029938,NaN,NaN,49.985718,NaN,NaN,NaN,AUS572,4869
86643181,AUS572,2025-12-14 18:46:04.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,231.819016,NaN,NaN,49.976238,NaN,NaN,NaN,AUS572,4869
86643182,AUS572,2025-12-14 18:51:04.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,232.835556,NaN,NaN,50.005142,NaN,NaN,NaN,AUS572,4869
86643183,AUS572,2025-12-14 18:56:04.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,232.526825,NaN,NaN,50.008038,NaN,NaN,NaN,AUS572,4869
86643184,AUS572,2025-12-14 20:56:05.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,238.569626,NaN,NaN,50.015503,NaN,NaN,NaN,AUS572,4869

# 2.

In [17]:
site_id = "AUS639"
test_site = df[df['site_alias'] == site_id]

In [18]:
test_site

,site_alias,timestamp,active_power_1,active_power_2,active_power_3,reactive_power_1,reactive_power_2,reactive_power_3,ac_voltage_1,ac_voltage_2,ac_voltage_3,ac_frequency_1,ac_frequency_2,ac_frequency_3,derating_active_flag,alias,zip_code
56229,AUS639,2025-01-22 00:02:52.000000,791.076477,NaN,NaN,-977.604370,NaN,NaN,245.994415,NaN,NaN,49.995316,NaN,NaN,NaN,AUS639,5062
56230,AUS639,2025-01-22 00:07:52.000000,768.189087,NaN,NaN,-1034.580322,NaN,NaN,246.317505,NaN,NaN,50.001839,NaN,NaN,NaN,AUS639,5062
56231,AUS639,2025-01-22 00:12:52.000000,666.256104,NaN,NaN,-1033.650635,NaN,NaN,246.168030,NaN,NaN,50.003437,NaN,NaN,NaN,AUS639,5062
56232,AUS639,2025-01-22 00:17:52.000000,660.728882,NaN,NaN,-964.000061,NaN,NaN,245.523087,NaN,NaN,50.011421,NaN,NaN,NaN,AUS639,5062
56233,AUS639,2025-01-22 00:22:52.000000,788.067810,NaN,NaN,-982.121460,NaN,NaN,245.926239,NaN,NaN,50.030113,NaN,NaN,NaN,AUS639,5062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86442925,AUS639,2025-12-08 23:37:53.000000,691.723816,NaN,NaN,-1033.416748,NaN,NaN,246.127655,NaN,NaN,50.001450,NaN,NaN,NaN,AUS639,5062
86442926,AUS639,2025-12-08 23:42:52.000000,679.818604,NaN,NaN,-1047.212891,NaN,NaN,246.116302,NaN,NaN,49.981407,NaN,NaN,NaN,AUS639,5062
86442927,AUS639,2025-12-08 23:47:53.000000,599.117432,NaN,NaN,-956.950439,NaN,NaN,245.293457,NaN,NaN,49.991680,NaN,NaN,NaN,AUS639,5062
86442928,AUS639,2025-12-08 23:52:52.000000,435.157043,NaN,NaN,-1110.888184,NaN,NaN,246.386215,NaN,NaN,49.987614,NaN,NaN,NaN,AUS639,5062
86442929,AUS639,2025-12-08 23:57:53.000000,550.764221,NaN,NaN,-1125.390869,NaN,NaN,245.946030,NaN,NaN,50.012295,NaN,NaN,NaN,AUS639,5062

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# pick the day you want
selected_date = pd.Timestamp("2025-06-15") 

start = selected_date.normalize()
end = start + pd.Timedelta(days=1)

day_site = df[(df["site_alias"] == site_id) &
              (pd.to_datetime(df["timestamp"]) >= start) &
              (pd.to_datetime(df["timestamp"]) < end)].copy()

day_site["timestamp"] = pd.to_datetime(day_site["timestamp"])
day_site = day_site.sort_values("timestamp")

day_site["active_power_total"] = day_site[["active_power_1", "active_power_2", "active_power_3"]].sum(axis=1)
day_site["reactive_power_total"] = day_site[["reactive_power_1", "reactive_power_2", "reactive_power_3"]].sum(axis=1)
day_site["voltage_avg"] = day_site[["ac_voltage_1", "ac_voltage_2", "ac_voltage_3"]].mean(axis=1)

fig, axes = plt.subplots(3, 1, sharex=True, figsize=(14, 11))

day_site.plot(x="timestamp", y="active_power_total", ax=axes[0], legend=False, color="tab:blue")
axes[0].set_title(f"Active power for {site_id} on {start:%Y-%m-%d}")
axes[0].set_ylabel("Active power")
axes[0].grid(True, alpha=0.3)

day_site.plot(x="timestamp", y="reactive_power_total", ax=axes[1], legend=False, color="tab:orange")
axes[1].set_title("Reactive power")
axes[1].set_ylabel("Reactive power")
axes[1].grid(True, alpha=0.3)

day_site.plot(x="timestamp", y="voltage_avg", ax=axes[2], legend=False, color="tab:green")
axes[2].set_title("Average AC voltage")
axes[2].set_ylabel("Voltage")
axes[2].grid(True, alpha=0.3)

axes[2].xaxis.set_major_locator(mdates.HourLocator(interval=1))
axes[2].xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
plt.setp(axes[2].get_xticklabels(), rotation=45)

plt.tight_layout()