# 01B: Exploratory Data Analysis

Characterises the fleet: site/circuit counts, geographic spread, export limits, key-table schemas, and single-day diagnostic plots.

In [1]:
import sys, pathlib
sys.path.insert(0, str(pathlib.Path('..').resolve()))
# sys.path.insert(0, str(pathlib.Path('lib').resolve()))

from shared.aws_config import aq, dread, s3_ls
from shared.ciccada_config import SA, SAI, AS4777, TABLES
from data_query.lib import explore_plots as ep
from data_query.lib import site_selection as ss
import pandas as pd
import numpy as np

## Sites and circuits

In [2]:
# -----------------------------------------------------------------------------
# Assumptions:
# sites  = physical locations (one row per address)
# circuits = monitoring points within a site (one row per phase/device)
# is_pv = True means it's a solar PV circuit (not load, battery, etc.)
# -----------------------------------------------------------------------------

site_count = aq("SELECT count(*) AS n_sites FROM sites", database=SAI)
print("Total sites:", site_count["n_sites"].iloc[0])

Total sites: 41393

In [3]:
circuit_counts = aq("""
    SELECT
        is_pv,
        count(*)          AS n_circuits,
        count(DISTINCT site_id) AS n_sites
    FROM circuits
    GROUP BY is_pv
    ORDER BY is_pv DESC
""", 
database=SAI)
circuit_counts

# is_pv=True rows are what the telemetry analysis is built on.
# The values below double count sites because many sites have both PV and non-PV circuits.

   is_pv  n_circuits  n_sites
0   True       79686    39733
1  False       91725    38191

In [4]:
# How many circuits per site?
circuits_per_site = aq("""
    SELECT
        circuit_count,
        count(*) AS n_sites
    FROM (
        SELECT site_id, count(*) AS circuit_count
        FROM circuits
        WHERE is_pv = True
        GROUP BY site_id
    )
    GROUP BY circuit_count
    ORDER BY circuit_count
""", database=SAI)
circuits_per_site

    circuit_count  n_sites
0               1    22454
1               2     3527
2               3    11556
3               4      432
4               5       51
5               6     1195
6               7       22
7               8       11
8               9      224
9              10        7
10             11        3
11             12      143
12             13        1
13             15       34
14             16        1
15             18       25
16             19        1
17             21        7
18             22        1
19             24       17
20             26        1
21             27        6
22             30        6
23             33        1
24             36        3
25             39        1
26             42        1
27             45        1
28             60        1

## Geographic spread

In [5]:
# -----------------------------------------------------------------------------
# Geographic spread — use meta_up23c, not sites
# -----------------------------------------------------------------------------

states = aq("""
    SELECT state, count(*) AS n_sites
    FROM meta_up23c
    GROUP BY state
    ORDER BY n_sites DESC
""", database=SAI)
states

  state  n_sites
0   NSW    26676
1   QLD    18276
2   VIC     5741
3    SA     4917
4    WA     2452
5   TAS     1086
6   ACT      944
7    NT      478

In [6]:
# -----------------------------------------------------------------------------
# Use partition_lookup (tiny table) rather than querying ts directly.
# Reading min/max timestamps from a billions-row table is expensive;
# the lookup table gives you the answer for free.
# -----------------------------------------------------------------------------

partitions = aq("SELECT * FROM partition_lookup ORDER BY year, month", database=SA)
partitions
# Each row = one (year, month) partition that exists in the ts table.
# The first and last rows tell you the data window.

    year  month  is_pv
0   2024      1  False
1   2024      1   True
2   2024      2   True
3   2024      2  False
4   2024      3  False
5   2024      3   True
6   2024      4  False
7   2024      4   True
8   2024      5   True
9   2024      5  False
10  2024      6  False
11  2024      6   True
12  2024      7  False
13  2024      7   True
14  2024      8  False
15  2024      8   True
16  2024      9  False
17  2024      9   True
18  2024     10   True
19  2024     10  False
20  2024     11  False
21  2024     11   True
22  2024     12   True
23  2024     12  False
24  2025      1  False
25  2025      1   True
26  2025      2  False
27  2025      2   True
28  2025      3  False
29  2025      3   True
30  2025      4   True
31  2025      4  False
32  2025      5  False
33  2025      5   True
34  2025      6  False
35  2025      6   True

In [7]:
unique_months = partitions[['year', 'month']].drop_duplicates().sort_values(['year', 'month'])

print("Data covers:")
print(f"  From: {unique_months['year'].iloc[0]}-{str(unique_months['month'].iloc[0]).zfill(2)}")
print(f"  To:   {unique_months['year'].iloc[-1]}-{str(unique_months['month'].iloc[-1]).zfill(2)}")
print(f"  Total months: {len(unique_months)}")

Data covers:
  From: 2024-01
  To:   2025-06
  Total months: 18

## Export limits (flex_export_detected)

In [8]:
aq('''
SELECT flex_export_detected, count(DISTINCT site_id) AS n_sites
FROM meta_up23c
WHERE is_pv = True
GROUP BY flex_export_detected
''', database='solar_analytics_iceberg')

   flex_export_detected  n_sites
0                 False    15609
1                  True      539

In [9]:
# ═══════════════════════════════════════════════════════════════════════════════
# flex_export_detected diagnostic checks
# ═══════════════════════════════════════════════════════════════════════════════

#  Check 1: Where are the flagged sites?
flex_by_dnsp = aq("""
    SELECT
        flex_export_detected,
        state,
        dnsp_name,
        count(DISTINCT site_id)  AS n_sites,
        round(avg(ac_capacity_kw), 1) AS avg_ac_kw,
        round(avg(export_limit_kw), 1) AS avg_export_limit_kw
    FROM meta_up23c
    WHERE is_pv = True
    GROUP BY flex_export_detected, state, dnsp_name
    ORDER BY flex_export_detected DESC, n_sites DESC
""", database='solar_analytics_iceberg')

print("Flex-export sites by state and DNSP:")
print(flex_by_dnsp.to_string(index=False))

# Check 2: Do flagged sites have explicit export limits?
# If export_limit_kw is set AND is less than ac_capacity_kw, 
# that's a signal the site really is constrained.

flex_export_limits = aq("""
    SELECT
        flex_export_detected,
        count(DISTINCT site_id) AS n_sites,
        sum(CASE WHEN export_limit_kw IS NOT NULL THEN 1 ELSE 0 END) AS has_export_limit,
        sum(CASE WHEN export_limit_kw IS NOT NULL
                  AND export_limit_kw < ac_capacity_kw THEN 1 ELSE 0 END)
            AS export_limit_below_nameplate
    FROM (
        SELECT DISTINCT site_id, ac_capacity_kw, export_limit_kw, flex_export_detected
        FROM meta_up23c
        WHERE is_pv = True
    )
    GROUP BY flex_export_detected
""", database='solar_analytics_iceberg')

print("\nExport limit breakdown:")
print(flex_export_limits.to_string(index=False))

Flex-export sites by state and DNSP:
 flex_export_detected state                   dnsp_name  n_sites  avg_ac_kw  avg_export_limit_kw
                 True   QLD                     Energex      150        9.8                  5.3
                 True   QLD                       Ergon      137       10.0                  5.0
                 True   NSW                   Essential       69       14.0                  4.4
                 True   NSW                   Endeavour       30        7.7                  5.6
                 True    SA                        SAPN       28        9.8                  5.0
                 True   NSW                     Ausgrid       22        8.3                  5.0
                 True   VIC                      Ausnet       20        7.9                  3.6
                 True    WA                        <NA>       18        7.8                  1.5
                 True   QLD                     Ausgrid       17        9.7                  5.0
                 True   TAS                 TasNetworks        9        9.2                  NaN
                 True   VIC                    Powercor        8        7.8                  5.0
                 True    WA               Western Power        7       11.8                  1.5
                 True   VIC               united energy        6        7.0                  5.0
                 True   VIC                      Jemena        6        7.9                  5.0
                 True   ACT                    Actewagl        5        5.8                  5.0
                 True    SA                        <NA>        3       15.2                  NaN
                 True    NT                        <NA>        1        5.0                  NaN
                 True    NT Power and Water Corporation        1       29.9                  0.0
                 True   VIC                     Ausgrid        1        7.0                  NaN
                 True   TAS                     Ausgrid        1        8.0                  NaN
                False   QLD                       Ergon     3286       13.2                  7.3
                False   NSW                     Ausgrid     2611       16.2                 10.2
                False   QLD                     Energex     2446       15.6                 16.1
                False   NSW                   Endeavour     1965       18.2                 10.5
                False   NSW                   Essential     1481       17.8                 11.1
                False    SA                        SAPN     1218       13.4                 10.3
                False   VIC                    Powercor      414       24.4                 21.0
                False   VIC                      Ausnet      407       21.7                 20.0
                False    WA                        <NA>      371        8.8                  7.3
                False   TAS                 TasNetworks      353       15.5                  6.7
                False   VIC               united energy      287       23.8                 21.7
                False   ACT                    Actewagl      188       23.2                  7.5
                False   VIC                      Jemena      130       16.8                 11.4
                False    WA               Western Power      117       20.5                  1.3
                False    NT                        <NA>       89       10.9                  2.1
                False   QLD                     Ausgrid       87       10.1                  5.0
                False   VIC                   CitiPower       61       18.0                 15.0
                False    NT Power and Water Corporation       32       37.1                  0.0
                False    SA                        <NA>       18       14.3                  NaN
                False   QLD                        <NA>       10       10.0                  NaN
                False   TAS                     Ausgrid        8       11.8                 10.0
                False   VIC                        <NA>        8       25.3                  NaN
                False   VIC                     Ausgrid        5       13.2                  NaN
                False   TAS                        <NA>        3        8.2                  NaN
                False    SA                     Ausgrid        3        6.0                  NaN
                False   VIC               Western Power        2       60.0                  NaN
                False    WA               Horizon Power        2        7.5                  NaN
                False   VIC                   Essential        2       57.5                  NaN
                False   NSW               united energy        1        5.0                  NaN
                False    WA                     Ausgrid        1        5.0                  NaN
                False   NSW                        <NA>        1        6.0                  NaN
                False   ACT                     Ausgrid        1        4.0                  NaN
                False    WA                       Ergon        1       29.9                  NaN

Export limit breakdown:
 flex_export_detected  n_sites  has_export_limit  export_limit_below_nameplate
                 True      539               104                            99
                False    15609               535                           427

## Schema of the key tables

In [10]:
# Schema discovery for all Iceberg tables.

iceberg_tables = [
    "ts",
    "meta_up23c",
    # Stage 1 rebuilds
    "structured_data_v2",
    "all_uncurtailedpv_v2",
    # Stage 2 rebuilds
    "conformance_voltvar_v2",
    "conformance_voltwatt_v2",
    "conformance_voltwattghi_v2",
    # not rebuilt. still legacy
    "conformance_antiisland",
    "conformance_sust_op_3w",
]

schemas = {}
for t in iceberg_tables:
    try:
        row = aq(f"SELECT * FROM {t} LIMIT 1", database=SAI)
        schemas[t] = pd.DataFrame({
            "column": row.columns.tolist(),
            "dtype":  [str(d) for d in row.dtypes.tolist()],
        })
        print(f"OK  {t:32s} {len(row.columns)} columns")
    except Exception as e:
        print(f"ERR {t:32s} {e}")

OK  ts                               16 columns
OK  meta_up23c                       38 columns
OK  structured_data_v2               23 columns
OK  all_uncurtailedpv_v2             17 columns
OK  conformance_voltvar_v2           34 columns
OK  conformance_voltwatt_v2          13 columns
OK  conformance_voltwattghi_v2       17 columns
OK  conformance_antiisland           9 columns
OK  conformance_sust_op_3w           9 columns

In [11]:
# Open up schemas here:
schemas['conformance_voltvar_v2']

                              column    dtype
0                            site_id    Int64
1                                day    Int32
2                          day_night   string
3                           p_kw_sum  float64
4         nonconformance_voltvar_sum  float64
5                      q_adverse_sum  float64
6                     q_inactive_sum  float64
7        q_significant_shortfall_sum  float64
8              q_near_conformant_sum  float64
9                q_major_surplus_sum  float64
10           curtailment_voltvar_sum  float64
11    nonconformance_voltvar_red_sum  float64
12      nonconformance_voltvar_count    Int64
13                   q_adverse_count    Int64
14                  q_inactive_count    Int64
15     q_significant_shortfall_count    Int64
16           q_near_conformant_count    Int64
17             q_major_surplus_count    Int64
18         curtailment_voltvar_count    Int64
19  nonconformance_voltvar_red_count    Int64
20        curtailment_eligible_count    Int64
21          null_uncurtailed_p_count    Int64
22                     exposed_count    Int64
23                   low_power_count    Int64
24           low_power_exposed_count    Int64
25               all_intervals_count    Int64
26                       total_count    Int64
27                      rating_basis   string
28             empirical_limit_basis   string
29                capability_profile   string
30               voltage_aggregation   string
31                    flex_selection   string
32                              year    Int32
33                             month    Int32

## Circuit bands

In [12]:
# Circuit count banded: makes the 1-to-60 range more interpretable
circuit_profile = aq("""
    SELECT
        CASE
            WHEN circuit_count = 1  THEN '1  - single phase'
            WHEN circuit_count = 2  THEN '2  - split or data gap'
            WHEN circuit_count = 3  THEN '3  - three phase'
            WHEN circuit_count <= 6 THEN '4-6 - multi-array or battery'
            ELSE                         '7+  - commercial / large site'
        END AS circuit_profile,
        count(*) AS n_sites,
        round(100.0 * count(*) / sum(count(*)) OVER (), 1) AS pct
    FROM (
        SELECT site_id, count(*) AS circuit_count
        FROM circuits
        WHERE is_pv = True
        GROUP BY site_id
    )
    GROUP BY 1
    ORDER BY min(circuit_count)
""", database=SAI)
circuit_profile

                 circuit_profile  n_sites   pct
0              1  - single phase    22454  56.5
1         2  - split or data gap     3527   8.9
2               3  - three phase    11556  29.1
3   4-6 - multi-array or battery     1678   4.2
4  7+  - commercial / large site      518   1.3

## Fleet characteristics

In [13]:
# -----------------------------------------------------------------------------
# Site summary four separate queries, one per count
# -----------------------------------------------------------------------------

n_sites         = aq("SELECT count(DISTINCT site_id) AS n FROM sites",       database=SAI)["n"].iloc[0]
n_meta_up23c    = aq("SELECT count(DISTINCT site_id) AS n FROM meta_up23c",  database=SAI)["n"].iloc[0]
n_pv_circuits   = aq("SELECT count(DISTINCT site_id) AS n FROM circuits WHERE is_pv = True", database=SAI)["n"].iloc[0]
#n_single_inv    = aq("SELECT count(*) AS n FROM meta_single_inverters",       database=SA) ["n"].iloc[0]

site_summary = pd.DataFrame([{
    "total_in_sites_table":       n_sites,
    "sites_in_meta_up23c":        n_meta_up23c,
    "sites_with_pv_circuit":      n_pv_circuits
#    "meta_single_inverters_rows": n_single_inv,
}])
site_summary

   total_in_sites_table  sites_in_meta_up23c  sites_with_pv_circuit
0                 41393                16148                  39733

## Single-day diagnostic plots

Pick a site + date, pull one day, convert to AEST, and plot. Two views:
- `plot_operational`: Volt-Watt + Volt-VAr response
- `plot_protective`: sustained-operation + anti-islanding (over/under-voltage)

In [14]:
# =============================================================================
# Select a response mode and pull a ranked site list
# =============================================================================
# RESPONSE_MODE : "voltwatt" | "voltvar" | "sust_op" | "sust_op_3w" | "antiisland"
# BEHAVIOUR     : "nonconforming" | "conforming"
# PLOT_TYPE     : "operational" | "protective"
# YEAR / MONTH  : MONTH=None ranks over the full year
#
# All conformance tables live in solar_analytics_iceberg (SAI).
# Ranking metric per mode:
#   voltwatt   — nonconformance_voltwatt_count
#   voltvar    — nonconformance_voltvar_red_count  (severe Q deviation only)
#                extra breakdown columns also pulled for context
#   sust_op    — nonconformance_sust_op_count
#   sust_op_3w — nonconformance_sust_op_3w_count
#   antiisland — nonconformance_antiisland_count
#
# NOTE on voltvar category name swap (pipeline bug from inherited code, old database):
#   q_minor_deviation  = 10–90% band  (larger shortfall — counterintuitively named)
#   q_major_deficit    = 90–110% band (near-miss   — counterintuitively named)
# =============================================================================

# =============================================================================
#### Q_impact = sign * (Q_kvar / Q_voltvar) ####
#         Q_impact < -10%   = Adverse
# -10% <= Q_impact <= +10%  = Inactive
# +10% <  Q_impact <= +90%  = Major deficit
# +90% <= Q_impact <= +110% = Minor deviation
# +110% < Q_impact          = Major surplus


# Rank sites for a mechanism
ranked = ss.rank_sites(
    mode="voltwatt", 
    aq_func=aq, 
    behaviour="conforming",
    year=2024, 
    min_days=20,
    n_results=100)
ranked

CONFORMING sites: voltwatt  |  period: 2024  |  table: conformance_voltwatt_v2
Returned 100 sites. Top = most conforming.

       site_id  nonconf_intervals  total_intervals  n_days  nonconf_pct
0   1805879028                  0                8     596          0.0
1    215923044                  0                2     668          0.0
2    737688694                  0               11     378          0.0
3   1103427156                  0              265     728          0.0
4    358691844                  0                2     218          0.0
..         ...                ...              ...     ...          ...
95  1209733559                  0                1     526          0.0
96   542062425                  0               93     726          0.0
97   527375167                  0                1     486          0.0
98   623558388                  0                1     348          0.0
99  1434416108                  0                2     721          0.0

[100 rows x 5 columns]

In [15]:
# 2. Pull that site nameplate/year/month/polarity
SITE_ID = ranked["site_id"].iloc[1]
# SITE_ID = 1033373679
# SITE_ID = 2134086510
df, info = ss.pull_site_telemetry(SITE_ID, "voltvar", aq, year=2024, month=None)

Site 215923044  |  NSW / Endeavour  |  5.0 kW  |  SMA Sunny Boy 5.0
Data: 2024-01-01 -> 2024-12-01  |  polarity 1
Auto-selected month 2 (of available [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
Rows: 8,342  (2024-02-01 -> 2024-03-01)

In [16]:
# 3. Which day to plot?
ss.suggest_days(df, "voltwatt")

Days with V > 253.0 V (most first):
t_stamp_aest
2024-02-02    2

  -> best candidate: 2024-02-02  (2 intervals)

t_stamp_aest
2024-02-02    2
Name: voltage, dtype: int64

### Operational plots

In [17]:
# 4. Plot pick a date that's actually in df
# df onlys pulls one month, so pick a date from the printed list above or from suggest_days().
print("Month pulled:", info["plot_year"], info["plot_month"])
print("Dates available:", sorted(df["t_stamp_aest"].dt.date.unique())[:5], "...")

ZOOM_DATE = "2024-07-11"
df_day = df[df["t_stamp_aest"].dt.date == pd.Timestamp(ZOOM_DATE).date()].copy()
assert len(df_day) > 0, f"No rows for {ZOOM_DATE}. Pick from the dates printed above or from suggest_days()."

ep.plot_operational(df_day, info["site_id"], info["ac_capacity_kw"], ZOOM_DATE, AS4777)

Month pulled: 2024 2
Dates available: [datetime.date(2024, 2, 1), datetime.date(2024, 2, 2), datetime.date(2024, 2, 3), datetime.date(2024, 2, 4), datetime.date(2024, 2, 5)] ...

AssertionError: No rows for 2024-07-11. Pick from the dates printed above or from suggest_days().

In [ ]:
# uses the month that pull_site_telemetry resolved
scatter_df = ss.pull_month_scatter(
    info["site_id"], 
    info["plot_year"],
    info["plot_month"], 
    aq
)
ep.plot_vvar_month_scatter(
    scatter_df, 
    info["site_id"], 
    info["ac_capacity_kw"],
    f"{info['plot_year']}-{info['plot_month']:02d}",
    manufacturer=info["manufacturer"]
)

### Operational diagnostics

In [ ]:
from data_query.lib import fleet_eda_diagnostics as fd

In [ ]:
stored_verdict = fd.fetch_stored_day_verdict(
    SITE_ID,
    ZOOM_DATE,
    aq,
    SAI,
)

recomputed = fd.recompute_vvar_day(
    SITE_ID,
    ZOOM_DATE,
    aq,
    SAI,
)

interval_summary, bucket_summary = (
    fd.summarise_recomputed_day(recomputed)
)

display(stored_verdict)
display(interval_summary)
display(recomputed)
display(bucket_summary)

In [ ]:
recomputed

In [ ]:
timestamp_status = recomputed[
    [
        "t_stamp_aest",
        "day_night",
        "V",
        "P_kW",
        "P_fraction_of_rated_proxy",
        "Q_kvar",
        "Q_voltvar",
        "Q_max_final",
        "Q_min_final",
        "capability_assessable",
        "outside_band",
        "Q_impact",
        "status",
    ]
]

display(timestamp_status)

In [ ]:
status_summary = (
    recomputed
    .groupby(["day_night", "status"], dropna=False)
    .size()
    .rename("intervals")
    .reset_index()
)

display(status_summary)

In [ ]:
high_voltage_check = fd.fetch_low_power_high_voltage(
    SITE_ID,
    info["plot_year"],
    info["plot_month"],
    aq,
    SAI,
)

display(high_voltage_check)

In [ ]:
stored_vw = fd.fetch_stored_voltwatt_day_verdict(
    SITE_ID,
    ZOOM_DATE,
    aq,
    SAI,
)

if stored_vw.empty:
    raise ValueError(
        f"No stored Volt-Watt result for site {SITE_ID}, {ZOOM_DATE}"
    )

# Recompute using the provenance recorded in the stored table.
vw_provenance = (
    stored_vw[
        [
            "rating_basis",
            "voltage_aggregation",
            "flex_selection",
        ]
    ]
    .drop_duplicates()
)

if len(vw_provenance) != 1:
    raise ValueError(
        "Expected exactly one Volt-Watt provenance configuration "
        f"for this site-day; found {len(vw_provenance)}."
    )

vw_options = vw_provenance.iloc[0].to_dict()

recomputed_vw = fd.recompute_voltwatt_day(
    SITE_ID,
    ZOOM_DATE,
    aq,
    SAI,
    **vw_options,
)

vw_timestamp_status = recomputed_vw[
    [
        "t_stamp_aest",
        "day_night",
        "V",
        "P_kW",
        "rating_kW",
        "P_limit_curve_kW",
        "tolerance_kW",
        "P_limit_with_tolerance_kW",
        "margin_to_limit_kW",
        "P_excess_kW",
        "exposed",
        "status",
    ]
]

vw_status_summary = (
    recomputed_vw
    .groupby(["day_night", "status"], dropna=False)
    .size()
    .rename("intervals")
    .reset_index()
)

display(stored_vw)
display(vw_timestamp_status)
display(vw_status_summary)

### Protective

In [ ]:
ep.plot_protective(df_day, info["site_id"], info["ac_capacity_kw"], ZOOM_DATE)